import { cva } from 'cva'

export const flexVariants = cva({
  base: '',
  variants: {
    display: {
      flex: 'flex',
      inline: 'inline-flex',
    },
    direction: {
      row: 'flex-row',
      rowReverse: 'flex-row-reverse',
      column: 'flex-column',
      columnReverse: 'flex-column-reverse',
    },
    align: {
      start: 'items-start',
      end: 'items-end',
      center: 'items-center',
      baseline: 'items-baseline',
      stretch: 'items-stretch',
    },
    justify: {
      start: 'justify-start',
      end: 'justify-end',
      center: 'justify-center',
      between: 'justify-between',
      around: 'justify-around',
    },
    wrap: {
      wrap: 'flex-wrap',
      nowrap: 'flex-nowrap',
      wrapReverse: 'flex-wrap-reverse',
    },
    gap: {
      '0': 'gap-0',
      '2xs': 'gap-2xs',
      xs: 'gap-xs',
      sm: 'gap-sm',
      md: 'gap-md',
      lg: 'gap-lg',
      xl: 'gap-xl',
      '2xl': 'gap-2xl',
      '3xl': 'gap-3xl',
      '4xl': 'gap-4xl',
    },
    gapX: {
      '0': 'gapx-0',
      '2xs': 'gapx-2xs',
      xs: 'gapx-xs',
      sm: 'gapx-sm',
      md: 'gapx-md',
      lg: 'gapx-lg',
      xl: 'gapx-xl',
      '2xl': 'gapx-2xl',
      '3xl': 'gapx-3xl',
      '4xl': 'gapx-4xl',
    },
    gapY: {
      '0': 'gapy-0',
      '2xs': 'gapy-2xs',
      xs: 'gapy-xs',
      sm: 'gapy-sm',
      md: 'gapy-md',
      lg: 'gapy-lg',
      xl: 'gapy-xl',
      '2xl': 'gapy-2xl',
      '3xl': 'gapy-3xl',
      '4xl': 'gapy-4xl',
    },
  },
  defaultVariants: {
    display: 'flex',
  },
})
