#!/usr/bin/env node
/**
 * Generates src/css/tokens/colors.css using the same mathematical approach
 * as the reference SCSS — ease-in-out interpolation of lightness and chroma
 * over 11 steps (50–950) per color, so the output can be compared against
 * Tailwind's palette.
 *
 * To adjust a palette entry, edit the `palette` object below and re-run:
 *   node scripts/generate-colors.js
 */

import { writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))

// ---------------------------------------------------------------------------
// Easing functions (ported from the reference SCSS)
// ---------------------------------------------------------------------------

const easeLinear = (t) => t
const easeInOut = (t) => t * t * (3 - 2 * t)
const easeIn = (t) => t * t
const easeOut = (t) => t * (2 - t)

function roundTo(value, decimals = 2) {
  const factor = 10 ** decimals
  return Math.round(value * factor) / factor
}

// ---------------------------------------------------------------------------
// Scale generator
//
// Produces 11 steps matching Tailwind's shade names: 50 → 950.
// t runs 0 (lightest) → 1 (darkest) uniformly across the 11 steps.
// ---------------------------------------------------------------------------

const SHADES = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950]

/**
 * @param {object} opts
 * @param {number}   opts.hue            Fixed hue (degrees)
 * @param {number}   opts.lightnessStart Lightness % at shade 50  (default 98)
 * @param {number}   opts.lightnessEnd   Lightness % at shade 950 (default 14)
 * @param {number}   opts.chromaStart    Chroma at shade 50
 * @param {number}   opts.chromaEnd      Chroma at shade 950
 * @param {Function} opts.ease           Easing function (default easeInOut)
 * @returns {Record<number, string>}
 */
function generateScale({
  hue,
  lightnessStart = 98,
  lightnessEnd = 14,
  chromaStart,
  chromaEnd,
  ease = easeInOut,
}) {
  const steps = SHADES.length
  return Object.fromEntries(
    SHADES.map((shade, i) => {
      const t = i / (steps - 1)
      const et = ease(t)

      const l = roundTo(lightnessStart - et * (lightnessStart - lightnessEnd), 2)
      const c = roundTo(chromaStart + et * (chromaEnd - chromaStart), 3)

      return [shade, `oklch(${l}% ${c} ${hue})`]
    })
  )
}

// ---------------------------------------------------------------------------
// Palette definition
//
// Each entry needs:
//   hue         — the defining hue angle for that color family
//   chromaStart — chroma at the lightest shade (50)
//   chromaEnd   — chroma at the darkest shade (950)
//
// Grays/neutrals have very low chroma. Vivid colors reach 0.2–0.3.
// Hues are chosen to place each family at its perceptually correct angle.
// ---------------------------------------------------------------------------

const palette = {
  // Neutral grays
  slate:   { hue: 258, chromaStart: 0.003, chromaEnd: 0.042 },
  gray:    { hue: 264, chromaStart: 0.002, chromaEnd: 0.028 },
  zinc:    { hue: 286, chromaStart: 0,     chromaEnd: 0.005 },
  neutral: { hue: 0,   chromaStart: 0,     chromaEnd: 0     },
  stone:   { hue: 67,  chromaStart: 0.001, chromaEnd: 0.004 },

  // Custom neutrals (not in Tailwind core)
  mauve:   { hue: 324, chromaStart: 0.003, chromaEnd: 0.008 },
  olive:   { hue: 107, chromaStart: 0.003, chromaEnd: 0.006 },
  mist:    { hue: 213, chromaStart: 0.002, chromaEnd: 0.004 },
  taupe:   { hue: 43,  chromaStart: 0.002, chromaEnd: 0.004 },

  // Warm chromas
  red:     { hue: 25,  chromaStart: 0.013, chromaEnd: 0.092 },
  orange:  { hue: 48,  chromaStart: 0.016, chromaEnd: 0.079 },
  amber:   { hue: 84,  chromaStart: 0.022, chromaEnd: 0.077 },
  yellow:  { hue: 95,  chromaStart: 0.026, chromaEnd: 0.066 },

  // Cool greens
  lime:    { hue: 130, chromaStart: 0.031, chromaEnd: 0.072 },
  green:   { hue: 151, chromaStart: 0.018, chromaEnd: 0.065 },
  emerald: { hue: 164, chromaStart: 0.021, chromaEnd: 0.051 },
  teal:    { hue: 183, chromaStart: 0.014, chromaEnd: 0.046 },

  // Blues
  cyan:    { hue: 212, chromaStart: 0.019, chromaEnd: 0.056 },
  sky:     { hue: 237, chromaStart: 0.013, chromaEnd: 0.066 },
  blue:    { hue: 261, chromaStart: 0.014, chromaEnd: 0.091 },
  indigo:  { hue: 277, chromaStart: 0.018, chromaEnd: 0.09  },

  // Purples & pinks
  violet:  { hue: 293, chromaStart: 0.016, chromaEnd: 0.141 },
  purple:  { hue: 305, chromaStart: 0.014, chromaEnd: 0.149 },
  fuchsia: { hue: 322, chromaStart: 0.017, chromaEnd: 0.136 },
  pink:    { hue: 350, chromaStart: 0.014, chromaEnd: 0.109 },
  rose:    { hue: 13,  chromaStart: 0.015, chromaEnd: 0.105 },
}

// ---------------------------------------------------------------------------
// Generate CSS
// ---------------------------------------------------------------------------

function generate() {
  const lines = [
    '/* Generated by scripts/generate-colors.js — do not edit by hand */',
    '',
    '@layer tokens {',
    '  :root {',
    '    --color-black: #000;',
    '    --color-white: #fff;',
    '    --color-transparent: transparent;',
    '    --color-inherit: inherit;',
    '    --color-current: currentcolor;',
  ]

  for (const [name, config] of Object.entries(palette)) {
    const scale = generateScale(config)
    lines.push('')
    for (const [shade, value] of Object.entries(scale)) {
      lines.push(`    --color-${name}-${shade}: ${value};`)
    }
  }

  lines.push('  }', '}', '')
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Write
// ---------------------------------------------------------------------------

const outPath = resolve(__dirname, '../src/css/tokens/color-gen.css')
writeFileSync(outPath, generate(), 'utf8')
console.log(`Written: ${outPath}`)
